---

charts:
  - name: qubership-kafka-service
    chart_file: operator/charts/helm/kafka-service/Chart.yaml
    values_file: operator/charts/helm/kafka-service/values.yaml
    image:
      - ghcr.io/${owner}/qubership-kafka-integration-tests:${tag}
      - ghcr.io/${owner}/qubership-kafka-crd-init:${tag}
      - ghcr.io/${owner}/qubership-kafka-service-operator:${tag}
      - ghcr.io/${owner}/qubership-kafka-monitoring:${tag}
      - ghcr.io/${owner}/qubership-kafka-backup-daemon:${tag}
      - ghcr.io/${owner}/qubership-docker-kafka-lag-exporter:${tag}
      - ghcr.io/${owner}/qubership-docker-cruise-control:${tag}
      - ghcr.io/${owner}/qubership-kafka-mirror-maker-monitoring:${tag}
      - ghcr.io/netcracker/qubership-disaster-recovery-daemon:#latest
      - ghcr.io/netcracker/qubership-docker-kubectl:#latest
  - name: qubership-kafka
    chart_file: operator/charts/helm/kafka/Chart.yaml
    values_file: operator/charts/helm/kafka/values.yaml
    image:
      - ghcr.io/${owner}/qubership-kafka-operator:${release}
      - ghcr.io/${owner}/qubership-docker-kafka:${release}
      - ghcr.io/netcracker/qubership-docker-kubectl:#latest
