{{- if .Values.integrationTests.install }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.integrationTests.service.name }}
  labels:
    {{- include "kafka-services.defaultLabels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.integrationTests.service.name }}
roleRef:
  kind: Role
  name: {{ .Values.integrationTests.service.name }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}