---
# This workflow is designed to clean up old Docker container versions in a GitHub repository.
name: Cleanup Old Docker Container Versions
run-name: "${{ github.event_name }} - ${{ github.actor }}"
on:
  schedule:
    - cron: "0 0 * * 0" # Runs weekly on Sunday at midnight
  workflow_dispatch:
    inputs:
      threshold-days:
        description: "Number of days to keep container versions"
        required: false
        default: "7"
      included-tags:
        description: "Tags to include for deletion"
        required: false
        default: ""
      excluded-tags:
        description: "Tags to exclude from deletion"
        required: false
        default: "release*"
      dry-run:
        description: "Enable dry-run mode"
        required: false
        default: "false"
      debug:
        description: "Enable debug mode"
        required: false
        default: "false"
permissions:
  contents: read

jobs:
  cleanup:
    name: "Cleanup Old Docker Container Versions"
    runs-on: ubuntu-latest
    steps:
      - name: "Summary"
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_ACTOR: ${{ github.actor }}
          THRESHOLD_DAYS: ${{ github.event.inputs.threshold-days || 7 }}
          INCLUDED_TAGS: ${{ github.event.inputs.included-tags || '*' }}
          EXCLUDED_TAGS: ${{ github.event.inputs.excluded-tags || 'latest,release*,*.*' }}
          DRY_RUN: ${{ github.event.inputs.dry-run || 'false' }}
          DEBUG: ${{ github.event.inputs.debug || 'false' }}
        run: |
          echo "**Event**: $GITHUB_EVENT_NAME"
          echo "**Actor**: $GITHUB_ACTOR"
          echo "**Threshold days**: $THRESHOLD_DAYS"
          echo "**Included tags**: $INCLUDED_TAGS"
          echo "**Excluded tags**: $EXCLUDED_TAGS"
          echo "**Dry-run**: $DRY_RUN"
          echo "**Debug**: $DEBUG"

      - name: "Run Container Package Cleanup Action"
        uses: netcracker/qubership-workflow-hub/actions/container-package-cleanup@396774180000abdb825cbf150b56cc59c6913db8 #v2.0.5
        with:
          threshold-days: ${{ github.event.inputs.threshold-days || 7 }}
          included-tags: ${{ github.event.inputs.included-tags || 'dev*' }}
          excluded-tags: ${{ github.event.inputs.excluded-tags || 'release*' }}
          dry-run: ${{ github.event.inputs.dry-run || 'false' }}
        env:
          PACKAGE_TOKEN: ${{ secrets.GH_RWD_PACKAGE_TOKEN }}
