---

# Workflow to build and publish multiple docker images based on configuration file (.qubership/docker.cfg)
# It builds only changed images based on the changeset detected.
# Configuration file example: config/examples/docker.cfg

name: "CI: Dev Docker Build"
run-name: "Ref: ${{ github.ref_name }}. On ${{ github.event_name }}"
on:
  push:
    branches:
      - "**"
    paths-ignore:
      - '.github/**'
      - "docs/**"
      - "CODE-OF-CONDUCT.md"
      - "CONTRIBUTING.md"
      - "LICENSE"
      - "README.md"
      - "SECURITY.md"
  pull_request:
    branches:
      - "**"
    paths-ignore:
      - '.github/**'
      - "docs/**"
      - "CODE-OF-CONDUCT.md"
      - "CONTRIBUTING.md"
      - "LICENSE"
      - "README.md"
      - "SECURITY.md"
  workflow_dispatch:
    inputs:
      tags:
        required: false
        type: string
        default: ""
        description: "Tags"
      dry-run:
        required: true
        type: boolean
        default: false
        description: "Dry run mode"
      replace-symbol:
        required: false
        type: string
        default: "_"
        description: "Symbol to replace in tags"

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.ref_type == 'branch' && format('build-branch-{0}', github.ref_name) || format('build-{0}', github.sha) }}
  cancel-in-progress: true

env:
  CONFIG_FILE: '.qubership/docker.cfg'

jobs:
  prepare:
    name: "Prepare Images and Metadata"
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.config.outputs.config }}
      tags: "${{ steps.meta.outputs.result }}"
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Changed Files
        if: github.event_name != 'workflow_dispatch'
        id: changed-files
        uses: tj-actions/changed-files@v47
        with:
          json: true
          write_output_files: true # .github/outputs/all_changed_files.json

      - name: Load Components and Platforms
        run: |
          if [[ "$GITHUB_EVENT_NAME" == "workflow_dispatch" ]]; then
            components=$(jq -c '.components' ${CONFIG_FILE})
          fi
          if [[ "$GITHUB_EVENT_NAME" == "pull_request" || "$GITHUB_EVENT_NAME" == "push" ]]; then
            all_changed_files=$(jq -c '.' .github/outputs/all_changed_files.json)
            if [ "$all_changed_files" != "null" ]; then
                components_file="${CONFIG_FILE}"
                files_file=".github/outputs/all_changed_files.json"

                jq -c --argjson files "$(cat "$files_file")" '
                  .components |
                  [ .[] | select(
                      . as $component |
                      any($files[];
                        [ $component.changeset[] as $ch | startswith($ch) ] | any
                      )
                    )
                  ]
                ' "$components_file" > /tmp/filtered_components.json
                echo "[DEBUG BEGIN] ========================================"
                cat /tmp/filtered_components.json
                echo "[DEBUG END] =========================================="

                jq '.components = input' ${CONFIG_FILE} /tmp/filtered_components.json > updated_config.json
                echo "[DEBUG BEGIN] ========================================"
                cat updated_config.json
                echo "[DEBUG END] =========================================="
            fi
          fi

      - name: Get Configuration File
        uses: netcracker/qubership-workflow-hub/actions/docker-config-resolver@c1a5c8c2d9c2a79f548134db1d095f36ee0f28e7 #v2.0.7
        id: config
        with:
          file-path: "updated_config.json"

      - name: Create tags for images
        uses: netcracker/qubership-workflow-hub/actions/metadata-action@c1a5c8c2d9c2a79f548134db1d095f36ee0f28e7 #v2.0.7
        id: meta
        with:
          default-template: "{{ref-name}}"
          extra-tags: ${{ github.event.inputs.tags || '' }}
          replace-symbol: ${{ github.event.inputs.replace-symbol || '_'}}

  build:
    name: ${{ matrix.component.name }} Image Build
    needs: [prepare]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        component: ${{ fromJson(needs.prepare.outputs.packages) }}
    steps:
      - name: Docker
        uses: netcracker/qubership-workflow-hub/actions/docker-action@c1a5c8c2d9c2a79f548134db1d095f36ee0f28e7 #v2.0.7
        with:
          ref: ${{ github.ref }}
          dry-run: ${{ github.event.inputs.dry-run || github.event_name == 'pull_request' }}
          download-artifact: false
          component: ${{ toJson(matrix.component) }}
          platforms: ${{ matrix.component.platforms }}
          tags: ${{ needs.prepare.outputs.tags }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
