name: "CI: Dev Docker Build"
run-name: "Ref: ${{ github.ref_name }}. On ${{ github.event_name }}"

on:
  workflow_dispatch:
    inputs:
      config-file:
        description: 'Docker build configuration file'
        required: false
        default: '.qubership/docker.cfg'
      tags:
        description: 'Tags'
        required: false
        type: string
        default: ''
      dry-run:
        description: 'Dry run'
        required: false
        type: boolean
        default: false
      replace-symbol:
        required: false
        type: string
        default: "_"
        description: "Symbol to replace in tags"
  push:
    branches:
    - '**'
    paths-ignore:
    - '.github/**'
    - 'docs/**'
    - 'CODE-OF-CONDUCT.md'
    - 'CONTRIBUTING.md'
    - 'LICENSE'
    - 'README.md'
    - 'SECURITY.md'
  pull_request:
    branches:
    - '**'
    paths-ignore:
    - '.github/**'
    - 'docs/**'
    - 'CODE-OF-CONDUCT.md'
    - 'CONTRIBUTING.md'
    - 'LICENSE'
    - 'README.md'
    - 'SECURITY.md'
permissions:
  contents: read

env:
  CONFIG_FILE: ${{ github.event.inputs.config-file || '.qubership/docker.cfg' }}

jobs:
  load-config:
    if: ${{ github.event_name != 'workflow_dispatch'}}
    runs-on: ubuntu-latest
    permissions:
      packages: read
    outputs:
      packages: ${{ steps.config.outputs.config }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.1
        with:
          persist-credentials: false

      - name: Get Configuration File
        uses: netcracker/qubership-workflow-hub/actions/docker-config-resolver@c1a5c8c2d9c2a79f548134db1d095f36ee0f28e7 #v2.0.7
        id: config
        with:
          file-path: "${{ env.CONFIG_FILE }}"

  docker-build:
    name: "Build and Publish Docker Image"
    needs: load-config
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        component: ${{ fromJson(needs.load-config.outputs.packages) }}
    steps:
      - name: "Checkout code"
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: "Create name"
        uses: netcracker/qubership-workflow-hub/actions/metadata-action@c1a5c8c2d9c2a79f548134db1d095f36ee0f28e7 # v2.0.7
        id: metadata
        with:
          default-template: "{{ref-name}}"
          extra-tags: ${{ github.event.inputs.tags || '' }}
          replace-symbol: ${{ github.event.inputs.replace-symbol || '_'}}

      - name: "Prepare tags"
        id: prepare_tags
        run: |
          BASE_TAG="${{ steps.metadata.outputs.result }}"
          EXTRA_TAG="${{ github.event.inputs.tags }}"
          if [ -n "$EXTRA_TAG" ]; then
            TAGS="${BASE_TAG}, ${EXTRA_TAG}"
          else
            TAGS="${BASE_TAG}"
          fi
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT

      - name: "Summary step"
        run: |
          echo "**Metadata:** ${{ steps.metadata.outputs.result }}" >> $GITHUB_STEP_SUMMARY
          echo "**Tags:** ${{ steps.prepare_tags.outputs.tags }}" >> $GITHUB_STEP_SUMMARY

      - name: "Build and Publish Docker Image"
        uses: netcracker/qubership-workflow-hub/actions/docker-action@c1a5c8c2d9c2a79f548134db1d095f36ee0f28e7 #v2.0.7
        with:
          custom-image-name: ${{ github.event.inputs.custom-image-name || '' }}
          component: ${{ toJson(matrix.component) }}
          platforms: ${{ matrix.component.platforms }}
          checkout: "false"
          tags: ${{ steps.prepare_tags.outputs.tags }}
          dry-run: ${{ github.event.inputs.dry-run || 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
