name: Build Artifacts
on:
  release: {}
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      publish_docker:
        description: "Publish image to ghcr.io"
        type: boolean
        default: true
        required: false
env:
  TAG_NAME: ${{ github.event.release.tag_name || github.ref }}
  PUSH: ${{ (github.event_name == 'workflow_dispatch' && inputs.publish_docker) || !startsWith(github.ref, 'refs/heads/dependabot') }}
  GITHUB_GROUP: ${{ github.repository_owner }}

jobs:
  changed-files:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    outputs:
      changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v47
        with:
          # files_yaml_from_source_file: .github/changed-files.yml
          json: true
          write_output_files: true
      - name: Set output
        run: |
          for f in .github/outputs/*; do
            echo "$f: $(cat $f)"
          done
  multiplatform_build:
    needs: changed-files
    strategy:
      fail-fast: false
      matrix:
        component:
          - name: qubership-kafka-integration-tests
            file: integration-tests/docker/Dockerfile
            context: integration-tests
            run: ${{ needs.changed-files.outputs.qubership-kafka-integration-tests_any_changed == 'true' || github.event_name == 'workflow_dispatch' }}
          - name: qubership-kafka-crd-init
            file: crd-init/docker/Dockerfile
            context: crd-init
            run: ${{ needs.changed-files.outputs.qubership-kafka-crd-init_any_changed == 'true' || github.event_name == 'workflow_dispatch' }}
          - name: qubership-kafka-operator
            file: Dockerfile
            context: .
            run: ${{ needs.changed-files.outputs.qubership-kafka-operator_any_changed == 'true' || github.event_name == 'workflow_dispatch' }}
          - name: qubership-kafka-service-operator
            file: Dockerfile
            context: .
            run: ${{ needs.changed-files.outputs.qubership-kafka-service-operator_any_changed == 'true' || github.event_name == 'workflow_dispatch' }}
          - name: qubership-kafka-service-transfer
            file: docker-transfer/kafka-service/Dockerfile
            context: ""
            run: ${{ needs.changed-files.outputs.qubership-kafka-service-transfer_any_changed == 'true' || github.event_name == 'workflow_dispatch' }}
          - name: qubership-kafka-transfer
            file: docker-transfer/kafka/Dockerfile
            context: ""
            run: ${{ needs.changed-files.outputs.qubership-kafka-transfer_any_changed == 'true' || github.event_name == 'workflow_dispatch' }}
          - name: qubership-kafka-backup-daemon
            file: backup-daemon/docker/Dockerfile
            context: backup-daemon
            run: ${{ needs.changed-files.outputs.qubership-kafka-backup-daemon_any_changed == 'true' || github.event_name == 'workflow_dispatch' }}
          - name: qubership-kafka-monitoring
            file: monitoring/docker/Dockerfile
            context: monitoring
            run: ${{ needs.changed-files.outputs.qubership-kafka-monitoring_any_changed == 'true' || github.event_name == 'workflow_dispatch' }}
          - name: qubership-docker-kafka
            file: docker-kafka/docker/Dockerfile
            context: docker-kafka
            run: ${{ needs.changed-files.outputs.qubership-docker-kafka_any_changed == 'true' || github.event_name == 'workflow_dispatch' }}
          - name: qubership-docker-akhq
            file: docker-akhq/docker/Dockerfile
            context: docker-akhq
            run: ${{ needs.changed-files.outputs.qubership-docker-akhq_any_changed == 'true' || github.event_name == 'workflow_dispatch' }}
          - name: qubership-docker-kafka-lag-exporter
            file: docker-kafka-lag-exporter/docker/Dockerfile
            context: docker-kafka-lag-exporter
            run: ${{ needs.changed-files.outputs.qubership-docker-kafka-lag-exporter_any_changed == 'true' || github.event_name == 'workflow_dispatch' }}
          - name: qubership-docker-cruise-control
            file: docker-cruise-control/docker/Dockerfile
            context: docker-cruise-control
            run: ${{ needs.changed-files.outputs.qubership-docker-cruise-control_any_changed == 'true' || github.event_name == 'workflow_dispatch' }}
          - name: qubership-kafka-mirror-maker-monitoring
            file: kafka-mirror-maker-monitoring/docker/Dockerfile
            context: kafka-mirror-maker-monitoring
            run: ${{ needs.changed-files.outputs.qubership-kafka-mirror-maker-monitoring_any_changed == 'true' || github.event_name == 'workflow_dispatch' }}
          - name: qubership-docker-kafka-mirror-maker
            file: kafka-mirror-maker/docker/Dockerfile
            context: kafka-mirror-maker
            run: ${{ needs.changed-files.outputs.qubership-docker-kafka-mirror-maker_any_changed == 'true' || github.event_name == 'workflow_dispatch' }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        if: ${{ matrix.component.run }}
        uses: actions/checkout@v4
      - name: Set up QEMU
        if: ${{ matrix.component.run }}
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        if: ${{ matrix.component.run }}
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        if: ${{ matrix.component.run }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${GITHUB_ACTOR}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Prepare Tag
        if: ${{ matrix.component.run }}
        run: echo "TAG_NAME=$(echo ${TAG_NAME} | sed 's@refs/tags/@@;s@refs/heads/@@;s@/@_@g')" >> $GITHUB_ENV
      - name: Prepare Group
        if: ${{ matrix.component.run }} && ${{ env.PUSH }}
        run: echo "GITHUB_GROUP=${GITHUB_GROUP,,}" >> $GITHUB_ENV
      - name: Build and push
        if: ${{ matrix.component.run }}
        uses: docker/build-push-action@v5
        with:
          # no-cache: true
          context: ${{ matrix.component.context }}
          file: ${{ matrix.component.file }}
          platforms: linux/amd64,linux/arm64
          push: ${{ env.PUSH }}
          tags: ghcr.io/${{ env.GITHUB_GROUP }}/${{ matrix.component.name }}:${{ env.TAG_NAME }}
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
