---
# This workflow executes several linters on changed files based on languages used in your code base whenever
# you push a code or open a pull request.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/super-linter/super-linter
# Configuration file for super-linter example:
# .github/super-linter.env
# Configuration files for individual linters should be placed in .github/linters

name: Lint Code Base

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      full_scan:
        type: boolean
        default: false
        required: false
        description: "Lint all codebase"
permissions:
  contents: read

jobs:
  super-linter:
    name: "Lint Code Base"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
    - name: "Get the common linters configuration"
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        ref: main # fix/superlinter-config
        repository: netcracker/.github
        persist-credentials: false
        path: common-configs
        sparse-checkout: |
          config/linters
    - name: "Move configs"
      run: |
        cp --update=none -vRT ./common-configs/config/linters /tmp/linters
        rm -rf ./common-configs
      # To report GitHub Actions status checks
    - name: "Checkout code"
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        # Full git history is needed to get a proper list of changed files within `super-linter`
        fetch-depth: 0
        persist-credentials: false
    - name: "Apply the common linters configuration"
      run: |
        mkdir -p ./.github/linters
        cp --update=none -vRT /tmp/linters ./.github/linters

    - name: "Load super-linter environment file"
      shell: bash
      run: |
        # shellcheck disable=2086
        if [ -f "${GITHUB_WORKSPACE}/.github/super-linter.env" ]; then
          echo "Applying local linter environment:"
          grep "\S" ${GITHUB_WORKSPACE}/.github/super-linter.env | grep -v "^#"
          grep "\S" ${GITHUB_WORKSPACE}/.github/super-linter.env | grep -v "^#" >> $GITHUB_ENV
        elif [ -f "/tmp/linters/super-linter.env" ]; then
          echo "::warning:: Local linter environment file .github/super-linter.env is not found"
          echo "Applying common linter environment:"
          grep "\S" /tmp/linters/super-linter.env | grep -v "^#"
          grep "\S" /tmp/linters/super-linter.env | grep -v "^#" >> $GITHUB_ENV
        fi
    - name: Cache Docker images.
      uses: ScribeMD/docker-cache@0.5.0
      with:
        key: docker-${{ runner.os }}
    
    - name: "Lint Code Base"
      uses: super-linter/super-linter/slim@47984f49b4e87383eed97890fe2dca6063bbd9c3 # v8.3.1
      env:
        VALIDATE_ALL_CODEBASE: ${{ inputs.full_scan || false }}
        # To report GitHub Actions status checks
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BRANCH: ${{ github.event.pull_request.base.ref || github.event.push.ref }}
