on: pull_request
name: test
jobs:
  matrix:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        component:
          - 1
          - 0
          - 1
          - 0
    steps:
      - run: |
          echo ${{ matrix.component }}
          exit ${{ matrix.component }}
  final-check:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [matrix]
    steps:
      - run: |
          result="${{ needs.matrix.result }}"
          if [[ $result == "success" || $result == "skipped" ]]; then
            exit 0
          else
            exit 1
          fi
